#
# 単体テスト
#
name: Unittest

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          brew install pipenv

      - name: Install dependencies for test
        run: pipenv install --dev

      - name: Unit test
        run: pipenv run python -m unittest discover -v tests
